apiVersion: v1
kind: ConfigMap
metadata:
  name: multitool-configmap #-{{ .Release.Name }}
data:
 HTTP_PORT: "{{ .Values.multitool.http_port }}"
 HTTPS_PORT: "{{ .Values.multitool.https_port }}"
