---
collections: []
roles:
  - name: dcjulian29.docker
    src: https://github.com/dcjulian29/ansible-role-docker.git
  - name: dcjulian29.nginx
    src: https://github.com/dcjulian29/ansible-role-nginx.git
