---
- name: Ensure directories for Teamcity server exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 0
    group: "{{ teamcity_group }}"
    mode: "0755"
  with_items:
    - "{{ teamcity_data_dir }}/{{ teamcity_name }}/logs/nginx"

- name: Include nginx role to host HTTPS endpoint
  ansible.builtin.include_role:
    name: dcjulian29.nginx
  vars:
    nginx_ssl_enabled: true
    nginx_error_log: "{{ teamcity_data_dir }}/{{ teamcity_name }}/logs/nginx/error.log warn"
    nginx_access_log: "{{ teamcity_data_dir }}/{{ teamcity_name }}/logs/nginx/access.log main buffer=16k flush=2m"
    nginx_vhosts:
      - acme: "{{ teamcity_https_acme }}"
        acme_challenge: '/var/www/letsencrypt/'
        extra_parameters: |
          location / {
            client_max_body_size 0;

            proxy_pass http://{{ tc_server.container.NetworkSettings.IPAddress }}:8111;

            proxy_http_version 1.1;
            proxy_read_timeout 1200;
            proxy_connect_timeout 240;

            proxy_set_header Host $server_name:$server_port;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
          }
        listen: "{{ teamcity_http_port }}"
        listen_ipv6: "{{ ansible_default_ipv6 | length > 0 }}"
        server_name: "{{ teamcity_server_fqdn }}"
        ssl_cert: "{{ teamcity_server_tls_cert }}"
        ssl_key: "{{ teamcity_server_tls_key }}"
        ssl_listen: 443
