---
# Pre tasks
- name: Create Nexus group
  become: true
  group:
    name: "{{ nexus_user_group }}"
    state: present
- name: Create Nexus user
  become: true
  user:
    name: "{{ nexus_user_name }}"

- name: Install JDK
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Detect firewall
  ansible.builtin.include_tasks: "firewall.yml"

# Tasks
- name: Create Nexus directories
  become: true
  file:
    group: "{{ nexus_user_group }}"
    owner: "{{ nexus_user_name }}"
    path: "{{ item }}"
    state: directory
  with_items:
  #  - "{{ nexus_directory_log }}"
  #  - "{{ nexus_directory_data }}"
  #  - "{{ nexus_directory_data }}/etc"
    - "{{ nexus_directory_package }}"
  #  - "{{ nexus_directory_tmp }}"

- name: Download Nexus
  become: true
  become_user: "{{ nexus_user_name }}"
  get_url:
    dest: "{{ nexus_directory_package }}/nexus-{{ nexus_version }}.tar.gz"
    url: "{{ nexus_download_url }}/nexus-{{ nexus_version }}-linux-x86_64.tar.gz"
    #url: https://download.sonatype.com/nexus/3/nexus-3.85.0-03-linux-x86_64.tar.gz

- name: Unpack Nexus
  become: true
  become_user: "{{ nexus_user_name }}"
  unarchive:
    remote_src: true
    creates: "{{ nexus_directory_home }}"
    dest: "{{ nexus_directory_package }}"
    src: "{{ nexus_directory_package }}/nexus-{{ nexus_version }}.tar.gz"
  tags:
    - nn

# Tasks
- name: Create Nexus directories
  become: true
  file:
    group: "{{ nexus_user_group }}"
    owner: "{{ nexus_user_name }}"
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nexus_directory_data }}/etc"
  tags:
    - nn

# - name: Link to Nexus Directory
#   become: true
#   become_user: "{{ nexus_user_name }}"
#   file:
#     dest: "{{ nexus_directory_home }}"
#     src: "{{ nexus_directory_home }}/nexus-{{ nexus_version }}"
#     state: link

- name: Add NEXUS_HOME for Nexus user
  become: true
  become_user: "{{ nexus_user_name }}"
  lineinfile:
    create: yes
    dest: "/home/{{ nexus_user_name }}/.bashrc"
    insertafter: EOF
    line: "export NEXUS_HOME={{ nexus_directory_home }}"
  tags:
    - nn

- name: Add run_as_user to Nexus.rc
  become: true
  become_user: "{{ nexus_user_name }}"
  lineinfile:
    create: yes
    dest: "{{ nexus_directory_home }}/bin/nexus.rc"
    insertafter: EOF
    line: "run_as_user=\"{{ nexus_user_name }}\""
    regexp: "^run_as_user"
  tags:
    - nn

- name: Raise nofile limit for Nexus user
  become: true
  pam_limits:
    domain: "{{ nexus_user_name }}"
    limit_type: "-"
    limit_item: nofile
    value: "{{ nexus_ulimit }}"
  tags:
    - nn

- name: Create Nexus service for SystemD
  become: true
  template:
    dest: /lib/systemd/system/nexus.service
    mode: 0644
    src: nexus.systemd.j2
  tags:
    - nn

- name: Ensure Nexus service is enabled for SystemD
  become: true
  systemd:
    daemon_reload: yes
    enabled: yes
    name: nexus
  when:
    - nexus_service_enabled
  tags:
    - nn

- name: Create Nexus vmoptions
  become: true
  become_user: "{{ nexus_user_name }}"
  template:
    dest: "{{ nexus_directory_home }}/bin/nexus.vmoptions"
    src: nexus.vmoptions.j2
  register: nexus_config_changed
  tags:
    - nn

- name: Create Nexus properties
  become: true
  become_user: "{{ nexus_user_name }}"
  template:
    dest: "{{ nexus_directory_data }}/etc/nexus.properties"
    src: nexus.properties.j2
  register: nexus_config_changed
  tags:
    - nn

- name: Lower Nexus disk space threshold
  become: true
  become_user: "{{ nexus_user_name }}"
  lineinfile:
    backrefs: yes
    dest: "{{ nexus_directory_home }}/etc/karaf/system.properties"
    insertafter: EOF
    line: "storage.diskCache.diskFreeSpaceLimit={{ nexus_configuration_disk_free_space_limit }}"
    regexp: ^storage\.diskCache\.diskFreeSpaceLimit
  when: nexus_configuration_disk_free_space_limit is not none
  register: nexus_config_changed
  tags:
    - nn

- name: Start Nexus service if enabled
  become: true
  service:
    enabled: yes
    name: nexus
    state: started
  when:
    - nexus_service_start_on_boot
    - not nexus_config_changed.changed
  tags:
    - skip_ansible_lint
  tags:
    - nn

- name: Ensure Nexus service is restarted
  become: true
  service:
    name: nexus
    state: restarted
  when:
    - nexus_service_start_on_boot
    - nexus_config_changed.changed
  tags:
    - skip_ansible_lint
    - nn

- name: Wait for Nexus port if started
  wait_for:
    port: "{{ nexus_port }}"
    state: started
    timeout: "{{ nexus_port_check_timeout }}"
  when:
    - nexus_service_start_on_boot
  tags:
    - nn
