---
prometheus_version: 3.5.0

node_exporter_targets: localhost:9090
prometheus_scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: "{{ node_exporter_targets }}"

  # - job_name: "prometheus"
  #   metrics_path: "{{ prometheus_metrics_path }}"
  #   static_configs:
  #     - targets:
  #         - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  # - job_name: "node"
  #   file_sd_configs:
  #     - files:
  #         - "{{ prometheus_config_dir }}/file_sd/node.yml"
prometheus_docker__data: /prometheus
prometheus_user_group: prometheus
prometheus_user_name: prometheus

node_targets: ["node_exporter:9100"]